{{ if .Values.default }}
{{ if and (.Values.default.clientid) (.Values.default.clientsecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "helm.fullname" . }}-default"
  labels:
    app: {{ template "helm.name" . }}
    chart: {{ template "helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  clientid: {{ .Values.default.clientid | b64enc | quote }}
  clientsecret: {{ .Values.default.clientsecret | b64enc | quote }}
{{ end }}
{{ end}}
