micronaut:
  application:
    name: forwardauth

  security:
    enabled: true

---
domain: https://dniel.eu.auth0.com/
token-endpoint: https://dniel.eu.auth0.com/oauth/token
authorize-url: https://dniel.eu.auth0.com/authorize
userinfo-endpoint: https://dniel.eu.auth0.com/userinfo
logout-endpoint:  https://dniel.eu.auth0.com/v2/logout

# set cookie max age for nonce to 5 min.
nonce-max-age: 300

default:
  name: default
  client-id: v1VM3YPVe7gdUELae1or2y7O1Mk3UAbx
  client-secret: avejbRMB1gWFgBGl1KESv_jb1gSr0eKNvxoHIhD4jkRlv4pyCsT7WXG5eKF0KntP
  audience: https://example.com
  scope: "profile openid email"
  redirect-uri: http://auth.example.test/signin
  token-cookie-domain: example.test
  #  return-to: https://vg.no
  claims:
    - sub
    - name
    - email
    - given_name
    - family_name
    - nickname

apps:
  - name: whoami.example.test
    required-permissions:
      - read:whoami
  - name: traefik.example.test
    required-permissions:
      - dashboard:traefik
  - name: www.example.test
    required-permissions:
      - read:www