spring:
  profiles:
    active: ${ENV:DEV}

server:
  port: ${PORT:8080}
  error:
    include-exception: true
    include-message: always
    include-stacktrace: never
    whitelabel:
      enabled: true

logging.pattern.level: "[%-40.-40(%mdc{userId})]"