######################################################################
# Workflow that zip, uploads artifact and notify SNS to start pipeline.
#
######################################################################
on:
  push:
    branches:
      - '*'
      - '!master'
      - '!main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        shell: bash
        run: |
          echo "::set-output name=application::forwardauth"
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: |
          echo ${{ steps.vars.outputs.application }}
          echo ${{ steps.vars.outputs.sha_short }}
          echo ${{ steps.vars.outputs.branch }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
      - name: List Build Folder
        shell: bash
        run: ls -laR build
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Docker/Dockerfile
          push: true
          tags: |
            dniel/${{ steps.vars.outputs.application }}:${{ steps.vars.outputs.branch }}
            dniel/${{ steps.vars.outputs.application }}:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Zip Folder
        id: zip_and_upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

        shell: bash
        run: |
          ARTIFACT_FILENAME=${{ steps.vars.outputs.application }}-${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}.zip
          S3_FILENAME=s3://${{ secrets.AWS_BUCKET }}/$ARTIFACT_FILENAME
          zip -r $ARTIFACT_FILENAME terraform
          aws s3 cp $ARTIFACT_FILENAME $S3_FILENAME
          echo "::set-output name=s3_filename::$S3_FILENAME"
          echo "::set-output name=artifact_filename::$ARTIFACT_FILENAME"
      - name: Uploaded file
        run: |
          echo ${{ steps.zip_and_upload.outputs.s3_filename }}
          echo ${{ steps.zip_and_upload.outputs.artifact_filename }}
      - name: Publish SNS Topic
        uses: nothingalike/sns-publish-topic@v1.6
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          MESSAGE: |
            {
              "reference":"${{ steps.zip_and_upload.outputs.s3_filename }}",
              "name": "${{ steps.vars.outputs.application }}",
              "commit": "${{ steps.vars.outputs.sha_short }}",
              "branch": "${{ steps.vars.outputs.branch }}",
              "provenance": "test123"
            }
          TOPIC_ARN: ${{ secrets.TOPIC_ARN }}
